/*
 * This class models the gui for choosing the difficulty of the game
 */
package gui;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.SwingUtilities;
import logic.SoundManager;
/**
 *
 * @author Eric
 */
public class ChooseDifficulty extends javax.swing.JFrame {
    
    private SoundManager mySoundManager;
    /**
     * Creates new form ChooseDifficulty 
     */
    public ChooseDifficulty() {
        initComponents();
        CustomCursor();
        mySoundManager = new SoundManager();
        mySoundManager.playMusic("music/difficulty.wav");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void CustomCursor()
    {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image img = toolkit.getImage("marioCursor.png");
        Point point = new Point(0, 0);
        Cursor cursor = toolkit.createCustomCursor(img, point, "Cursor");
        
        setCursor(cursor);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeBtn = new javax.swing.JButton();
        chooseDiffLabel = new javax.swing.JLabel();
        easyBtn = new javax.swing.JButton();
        medBtn = new javax.swing.JButton();
        hardBtn = new javax.swing.JButton();
        bkg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Mario MineSweeper - Difficulty");
        setPreferredSize(new java.awt.Dimension(500, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        homeBtn.setBackground(new java.awt.Color(153, 204, 255));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/home button.png"))); // NOI18N
        homeBtn.setContentAreaFilled(false);
        homeBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/home button clicked.png"))); // NOI18N
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(homeBtn);
        homeBtn.setBounds(0, 0, 70, 74);

        chooseDiffLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/choose difficulty2.png"))); // NOI18N
        getContentPane().add(chooseDiffLabel);
        chooseDiffLabel.setBounds(150, 0, 210, 120);

        easyBtn.setBackground(new java.awt.Color(204, 255, 255));
        easyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/easy2.png"))); // NOI18N
        easyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyBtnMouseClicked(evt);
            }
        });
        getContentPane().add(easyBtn);
        easyBtn.setBounds(130, 160, 220, 70);

        medBtn.setBackground(new java.awt.Color(204, 255, 255));
        medBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/medium2.png"))); // NOI18N
        medBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medBtnMouseClicked(evt);
            }
        });
        getContentPane().add(medBtn);
        medBtn.setBounds(130, 270, 220, 70);

        hardBtn.setBackground(new java.awt.Color(204, 255, 255));
        hardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/hard2.png"))); // NOI18N
        hardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hardBtnMouseClicked(evt);
            }
        });
        getContentPane().add(hardBtn);
        hardBtn.setBounds(130, 380, 220, 70);

        bkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/bkg.png"))); // NOI18N
        bkg.setText("jLabel1");
        getContentPane().add(bkg);
        bkg.setBounds(0, 0, 500, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt))
        {
            mySoundManager.stopMusic();
            this.setVisible(false);
            new MainMenu().setVisible(true);
        }
    }//GEN-LAST:event_homeBtnMouseClicked

    private void easyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyBtnMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt))
        {
            mySoundManager.stopMusic();
            this.setVisible(false);
            new Game("easy", null).setVisible(true);
        }
    }//GEN-LAST:event_easyBtnMouseClicked

    private void medBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medBtnMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt))
        {
            mySoundManager.stopMusic();
            this.setVisible(false);
            new Game("medium", null).setVisible(true);
        }
    }//GEN-LAST:event_medBtnMouseClicked

    private void hardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardBtnMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt))
        {
            mySoundManager.stopMusic();
            this.setVisible(false);
            new Game("hard", null).setVisible(true);
        }
    }//GEN-LAST:event_hardBtnMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bkg;
    private javax.swing.JLabel chooseDiffLabel;
    private javax.swing.JButton easyBtn;
    private javax.swing.JButton hardBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton medBtn;
    // End of variables declaration//GEN-END:variables
}
