/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.*;
import logic.*;
/**
 *
 * @author Eric
 */
public class MainMenu extends javax.swing.JFrame {
    private SoundManager mySoundManager;
    private FileReader reader;
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        CustomCursor();
        mySoundManager = new SoundManager();
        mySoundManager.playMusic("music/menu.wav");
        reader = new FileReader();
        
        //these buttons are set invisible since their respective features will be implemented in the future.
        highScoresBtn.setVisible(false);
        helpBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void CustomCursor()
    {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image img = toolkit.getImage("marioCursor.png");
        Point point = new Point(0, 0);
        Cursor cursor = toolkit.createCustomCursor(img, point, "Cursor");
        
        setCursor(cursor);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startBtn = new javax.swing.JButton();
        helpBtn = new javax.swing.JButton();
        loadBtn = new javax.swing.JButton();
        highScoresBtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        bkg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Mario MineSweeper");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(500, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        startBtn.setBackground(new java.awt.Color(204, 255, 255));
        startBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        startBtn.setForeground(new java.awt.Color(0, 255, 0));
        startBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/start game2.png"))); // NOI18N
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });
        getContentPane().add(startBtn);
        startBtn.setBounds(110, 160, 281, 82);

        helpBtn.setBackground(new java.awt.Color(204, 255, 255));
        helpBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        helpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/question block.png"))); // NOI18N
        helpBtn.setMaximumSize(new java.awt.Dimension(66, 66));
        helpBtn.setMinimumSize(new java.awt.Dimension(66, 66));
        helpBtn.setPreferredSize(new java.awt.Dimension(66, 66));
        helpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpBtnMouseClicked(evt);
            }
        });
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });
        getContentPane().add(helpBtn);
        helpBtn.setBounds(420, 490, 66, 66);

        loadBtn.setBackground(new java.awt.Color(204, 255, 255));
        loadBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        loadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/load game2.png"))); // NOI18N
        loadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadBtnMouseClicked(evt);
            }
        });
        getContentPane().add(loadBtn);
        loadBtn.setBounds(110, 280, 281, 82);

        highScoresBtn.setBackground(new java.awt.Color(255, 255, 204));
        highScoresBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/high scores.png"))); // NOI18N
        getContentPane().add(highScoresBtn);
        highScoresBtn.setBounds(100, 390, 300, 70);

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/title2.png"))); // NOI18N
        getContentPane().add(title);
        title.setBounds(80, 0, 350, 140);

        bkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/bkg.png"))); // NOI18N
        getContentPane().add(bkg);
        bkg.setBounds(0, 0, 500, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mySoundManager.stopMusic();
        new ChooseDifficulty().setVisible(true);
    }//GEN-LAST:event_startBtnActionPerformed

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mySoundManager.stopMusic();
        new Help().setVisible(true);
    }//GEN-LAST:event_helpBtnActionPerformed

    private void helpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_helpBtnMouseClicked

    private void loadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        mySoundManager.stopMusic();
        new LoadGame().setVisible(true);
    }//GEN-LAST:event_loadBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bkg;
    private javax.swing.JButton helpBtn;
    private javax.swing.JButton highScoresBtn;
    private javax.swing.JButton loadBtn;
    private javax.swing.JButton startBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
