/*
 * This class models the gui for saving the game
 */
package gui;

import java.awt.*;
import logic.FileWriter;
import logic.FileReader;
import logic.GameManager;
/**
 *
 * @author Eric
 */
public class SaveGame extends javax.swing.JFrame {

    private FileWriter writer;
    private FileReader reader;
    private GameManager myGame;
    /**
     * Creates new form SaveGame
     */
    public SaveGame(GameManager game) {
        initComponents();
        CustomCursor();
        writer = new FileWriter();
        this.myGame = game;
        reader = new FileReader();
        String info1 = reader.loadInfo("saves/save1Info.txt");
        String info2 = reader.loadInfo("saves/save2Info.txt");
        String info3 = reader.loadInfo("saves/save3Info.txt");
        setSaveInfo(info1);
        setSaveInfo(info2);
        setSaveInfo(info3);
    }

    public void CustomCursor()
    {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image img = toolkit.getImage("marioCursor.png");
        Point point = new Point(0, 0);
        Cursor cursor = toolkit.createCustomCursor(img, point, "Cursor");
        
        setCursor(cursor);
    }
    
    public void setSaveInfo(String info)
    {
        //separate save info in array
            String[] allInfo = info.split(",");
            //change gui based on the info of each save
            if(allInfo[0].equals("save1"))
            {
                save1Difficulty.setText(allInfo[1]);
                if(allInfo[1].equals("easy"))
                    save1Difficulty.setForeground(new Color(81, 255, 69));
                else if(allInfo[1].equals("medium"))
                    save1Difficulty.setForeground(new Color(241, 255, 33));
                else if(allInfo[1].equals("hard"))
                    save1Difficulty.setForeground(new Color(165, 5, 5));
                
                save1Time.setText(allInfo[2]);
                save1Flags.setText(allInfo[3]);
            }
            else if(allInfo[0].equals("save2"))
            {
                save2Difficulty.setText(allInfo[1]);
                if(allInfo[1].equals("easy"))
                    save2Difficulty.setForeground(new Color(81, 255, 69));
                else if(allInfo[1].equals("medium"))
                    save2Difficulty.setForeground(new Color(241, 255, 33));
                else if(allInfo[1].equals("hard"))
                    save2Difficulty.setForeground(new Color(165, 5, 5));
                
                save2Time.setText(allInfo[2]);
                save2Flags.setText(allInfo[3]);
            }
            else if(allInfo[0].equals("save3"))
            {
                save3Difficulty.setText(allInfo[1]);
                if(allInfo[1].equals("easy"))
                    save3Difficulty.setForeground(new Color(81, 255, 69));
                else if(allInfo[1].equals("medium"))
                    save3Difficulty.setForeground(new Color(241, 255, 33));
                else if(allInfo[1].equals("hard"))
                    save3Difficulty.setForeground(new Color(165, 5, 5));
                
                save3Time.setText(allInfo[2]);
                save3Flags.setText(allInfo[3]);
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        save2 = new javax.swing.JPanel();
        save2Btn = new javax.swing.JButton();
        save2Name = new javax.swing.JLabel();
        save2Time = new javax.swing.JLabel();
        save2Flags = new javax.swing.JLabel();
        save2Difficulty = new javax.swing.JLabel();
        save2Bkg = new javax.swing.JLabel();
        save1 = new javax.swing.JPanel();
        save1Btn = new javax.swing.JButton();
        save1Name = new javax.swing.JLabel();
        save1Time = new javax.swing.JLabel();
        save1Flags = new javax.swing.JLabel();
        save1Difficulty = new javax.swing.JLabel();
        save1Bkg = new javax.swing.JLabel();
        save3 = new javax.swing.JPanel();
        save3Btn = new javax.swing.JButton();
        save3Name = new javax.swing.JLabel();
        save3Time = new javax.swing.JLabel();
        save3Flags = new javax.swing.JLabel();
        save3Difficulty = new javax.swing.JLabel();
        save3Bkg = new javax.swing.JLabel();
        bkg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Save Game");
        setMaximumSize(new java.awt.Dimension(500, 374));
        setMinimumSize(new java.awt.Dimension(500, 374));
        setPreferredSize(new java.awt.Dimension(500, 374));
        setResizable(false);
        getContentPane().setLayout(null);

        save2.setBackground(new java.awt.Color(255, 204, 153));
        save2.setMaximumSize(new java.awt.Dimension(290, 80));
        save2.setPreferredSize(new java.awt.Dimension(290, 80));
        save2.setLayout(null);

        save2Btn.setBackground(new java.awt.Color(228, 92, 29));
        save2Btn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save2Btn.setForeground(new java.awt.Color(255, 255, 255));
        save2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/save icon.gif"))); // NOI18N
        save2Btn.setText("Save");
        save2Btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        save2Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save2Btn.setIconTextGap(1);
        save2Btn.setMaximumSize(new java.awt.Dimension(70, 80));
        save2Btn.setMinimumSize(new java.awt.Dimension(70, 80));
        save2Btn.setPreferredSize(new java.awt.Dimension(70, 80));
        save2Btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        save2Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save2BtnMouseClicked(evt);
            }
        });
        save2.add(save2Btn);
        save2Btn.setBounds(220, 0, 70, 80);

        save2Name.setBackground(new java.awt.Color(255, 204, 204));
        save2Name.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save2Name.setForeground(new java.awt.Color(255, 255, 255));
        save2Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save2Name.setText("Save 2");
        save2Name.setToolTipText("");
        save2Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        save2.add(save2Name);
        save2Name.setBounds(0, 1, 100, 30);

        save2Time.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save2Time.setForeground(new java.awt.Color(255, 255, 255));
        save2Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save2Time.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/clock.png"))); // NOI18N
        save2Time.setText("-");
        save2Time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        save2.add(save2Time);
        save2Time.setBounds(0, 30, 100, 50);

        save2Flags.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save2Flags.setForeground(new java.awt.Color(255, 255, 255));
        save2Flags.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save2Flags.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/flag.png"))); // NOI18N
        save2Flags.setText("-");
        save2Flags.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        save2.add(save2Flags);
        save2Flags.setBounds(100, 30, 120, 50);

        save2Difficulty.setBackground(new java.awt.Color(255, 204, 204));
        save2Difficulty.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save2Difficulty.setForeground(new java.awt.Color(255, 255, 255));
        save2Difficulty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save2Difficulty.setText("-----");
        save2Difficulty.setToolTipText("");
        save2Difficulty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        save2.add(save2Difficulty);
        save2Difficulty.setBounds(100, 1, 120, 30);

        save2Bkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/save bkg.png"))); // NOI18N
        save2Bkg.setText("jLabel2");
        save2.add(save2Bkg);
        save2Bkg.setBounds(0, 0, 290, 80);

        getContentPane().add(save2);
        save2.setBounds(100, 140, 290, 80);

        save1.setBackground(new java.awt.Color(255, 204, 153));
        save1.setMaximumSize(new java.awt.Dimension(290, 80));
        save1.setPreferredSize(new java.awt.Dimension(290, 80));
        save1.setLayout(null);

        save1Btn.setBackground(new java.awt.Color(228, 92, 29));
        save1Btn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save1Btn.setForeground(new java.awt.Color(255, 255, 255));
        save1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/save icon.gif"))); // NOI18N
        save1Btn.setText("Save");
        save1Btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        save1Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save1Btn.setIconTextGap(1);
        save1Btn.setMaximumSize(new java.awt.Dimension(70, 80));
        save1Btn.setMinimumSize(new java.awt.Dimension(70, 80));
        save1Btn.setPreferredSize(new java.awt.Dimension(70, 80));
        save1Btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        save1Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save1BtnMouseClicked(evt);
            }
        });
        save1.add(save1Btn);
        save1Btn.setBounds(220, 0, 70, 80);

        save1Name.setBackground(new java.awt.Color(255, 204, 204));
        save1Name.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save1Name.setForeground(new java.awt.Color(255, 255, 255));
        save1Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save1Name.setText("Save 1");
        save1Name.setToolTipText("");
        save1Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        save1.add(save1Name);
        save1Name.setBounds(0, 1, 100, 30);

        save1Time.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save1Time.setForeground(new java.awt.Color(255, 255, 255));
        save1Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save1Time.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/clock.png"))); // NOI18N
        save1Time.setText("-");
        save1Time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        save1.add(save1Time);
        save1Time.setBounds(0, 30, 100, 50);

        save1Flags.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save1Flags.setForeground(new java.awt.Color(255, 255, 255));
        save1Flags.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save1Flags.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/flag.png"))); // NOI18N
        save1Flags.setText("-");
        save1Flags.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        save1.add(save1Flags);
        save1Flags.setBounds(100, 30, 120, 50);

        save1Difficulty.setBackground(new java.awt.Color(255, 204, 204));
        save1Difficulty.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save1Difficulty.setForeground(new java.awt.Color(255, 255, 255));
        save1Difficulty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save1Difficulty.setText("-----");
        save1Difficulty.setToolTipText("");
        save1Difficulty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        save1.add(save1Difficulty);
        save1Difficulty.setBounds(100, 1, 120, 30);

        save1Bkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/save bkg.png"))); // NOI18N
        save1Bkg.setText("jLabel2");
        save1.add(save1Bkg);
        save1Bkg.setBounds(0, 0, 290, 80);

        getContentPane().add(save1);
        save1.setBounds(100, 10, 290, 80);

        save3.setBackground(new java.awt.Color(255, 204, 153));
        save3.setMaximumSize(new java.awt.Dimension(290, 80));
        save3.setPreferredSize(new java.awt.Dimension(290, 80));
        save3.setLayout(null);

        save3Btn.setBackground(new java.awt.Color(228, 92, 29));
        save3Btn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save3Btn.setForeground(new java.awt.Color(255, 255, 255));
        save3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/save icon.gif"))); // NOI18N
        save3Btn.setText("Save");
        save3Btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        save3Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save3Btn.setIconTextGap(1);
        save3Btn.setMaximumSize(new java.awt.Dimension(70, 80));
        save3Btn.setMinimumSize(new java.awt.Dimension(70, 80));
        save3Btn.setPreferredSize(new java.awt.Dimension(70, 80));
        save3Btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        save3Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save3BtnMouseClicked(evt);
            }
        });
        save3.add(save3Btn);
        save3Btn.setBounds(220, 0, 70, 80);

        save3Name.setBackground(new java.awt.Color(255, 204, 204));
        save3Name.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save3Name.setForeground(new java.awt.Color(255, 255, 255));
        save3Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save3Name.setText("Save 3");
        save3Name.setToolTipText("");
        save3Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        save3.add(save3Name);
        save3Name.setBounds(0, 1, 100, 30);

        save3Time.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save3Time.setForeground(new java.awt.Color(255, 255, 255));
        save3Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save3Time.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/clock.png"))); // NOI18N
        save3Time.setText("-");
        save3Time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        save3.add(save3Time);
        save3Time.setBounds(0, 30, 100, 50);

        save3Flags.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save3Flags.setForeground(new java.awt.Color(255, 255, 255));
        save3Flags.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save3Flags.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/flag.png"))); // NOI18N
        save3Flags.setText("-");
        save3Flags.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        save3.add(save3Flags);
        save3Flags.setBounds(100, 30, 120, 50);

        save3Difficulty.setBackground(new java.awt.Color(255, 204, 204));
        save3Difficulty.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        save3Difficulty.setForeground(new java.awt.Color(255, 255, 255));
        save3Difficulty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save3Difficulty.setText("-----");
        save3Difficulty.setToolTipText("");
        save3Difficulty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        save3.add(save3Difficulty);
        save3Difficulty.setBounds(100, 1, 120, 30);

        save3Bkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/save bkg.png"))); // NOI18N
        save3Bkg.setText("jLabel2");
        save3.add(save3Bkg);
        save3Bkg.setBounds(0, 0, 290, 80);

        getContentPane().add(save3);
        save3.setBounds(100, 250, 290, 80);

        bkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/bkg.png"))); // NOI18N
        getContentPane().add(bkg);
        bkg.setBounds(0, 0, 500, 374);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void save1BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1BtnMouseClicked
        // TODO add your handling code here:
        writer.saveGame(myGame, "save1");
        writer.saveInfo(myGame, "save1");
        this.setVisible(false);
    }//GEN-LAST:event_save1BtnMouseClicked

    private void save2BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save2BtnMouseClicked
        // TODO add your handling code here:
        writer.saveGame(myGame, "save2");
        writer.saveInfo(myGame, "save2");
        this.setVisible(false);
    }//GEN-LAST:event_save2BtnMouseClicked

    private void save3BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save3BtnMouseClicked
        // TODO add your handling code here:
        writer.saveGame(myGame, "save3");
        writer.saveInfo(myGame, "save3");
        this.setVisible(false);
    }//GEN-LAST:event_save3BtnMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bkg;
    private javax.swing.JPanel save1;
    private javax.swing.JLabel save1Bkg;
    private javax.swing.JButton save1Btn;
    private javax.swing.JLabel save1Difficulty;
    private javax.swing.JLabel save1Flags;
    private javax.swing.JLabel save1Name;
    private javax.swing.JLabel save1Time;
    private javax.swing.JPanel save2;
    private javax.swing.JLabel save2Bkg;
    private javax.swing.JButton save2Btn;
    private javax.swing.JLabel save2Difficulty;
    private javax.swing.JLabel save2Flags;
    private javax.swing.JLabel save2Name;
    private javax.swing.JLabel save2Time;
    private javax.swing.JPanel save3;
    private javax.swing.JLabel save3Bkg;
    private javax.swing.JButton save3Btn;
    private javax.swing.JLabel save3Difficulty;
    private javax.swing.JLabel save3Flags;
    private javax.swing.JLabel save3Name;
    private javax.swing.JLabel save3Time;
    // End of variables declaration//GEN-END:variables
}
